### PR TITLE
Minimal Py3 compat fixes.

### LINKED ISSUE #3: Unicode errors with Python 3
With Python 2.7.10:
```
In [1]: import sorbic.db
In [2]: mydb = sorbic.db.DB('/tmp/sorbic')
```
In Python 3.5.0:
```
In [1]: import sorbic.db
In [2]: mydb = sorbic.db.DB('/tmp/sorbic')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-37737e16cf84> in <module>()
----> 1 mydb = sorbic.db.DB('/tmp/sorbic')

/usr/lib/python3.5/site-packages/sorbic/db.py in __init__(self, root, key_delim, hash_limit, key_hash, fmt, fmt_map, header_len, serial)
     53             self.fmt,
     54             self.fmt_map,
---> 55             self.header_len)
     56         self.write_stor_funcs = self.__gen_write_stor_funcs()
     57         self.read_stor_funcs = self.__gen_read_stor_funcs()

/usr/lib/python3.5/site-packages/sorbic/ind/hdht.py in __init__(self, root, key_delim, hash_limit, key_hash, fmt, fmt_map, header_len, serial)
     58         self.header_len = header_len
     59         self.crypt_func = self.__crypt_func()
---> 60         self.key_size = self.__gen_key_size()
     61         self.fmt = fmt.replace('K', str(self.key_size))
     62         self.bucket_size = self.__gen_bucket_size()

/usr/lib/python3.5/site-packages/sorbic/ind/hdht.py in __gen_key_size(self)
     77         Return the length of the crypt_key
     78         '''
---> 79         return len(self.raw_crypt_key('sorbic is awesome'))
     80 
     81     def __gen_bucket_size(self):

/usr/lib/python3.5/site-packages/sorbic/ind/hdht.py in raw_crypt_key(self, key)
    123         Return the crypted key
    124         '''
--> 125         return self.crypt_func(key.lstrip(self.key_delim)).digest()
    126 
    127     def entry_root(self, key):

TypeError: Unicode-objects must be encoded before hashing
```

### PR DESCRIPTION
**Pull request by s0undt3ch**
Fixes #3

### CODE REVIEW

**Comment by thatch45** [comment]
Tests still don't run...

**Comment by s0undt3ch** [comment]
started to fail because of this change?
There's lot's more to fix for py3 support...

On 22 October 2015 at 22:21, Thomas S Hatch notifications@github.com
wrote:

> Tests still don't run...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thatch45/sorbic/pull/4#issuecomment-150359552.

## 

Pedro Algarvio

**Comment by thatch45** [comment]
py2 still works :) yes there would be a lot to get it on py3, but if it works on py3 we don't need py2 anymore

**Comment by s0undt3ch** [comment]
We should bring six into the equation, it will greatly simplify supporting
both, however, if all you're after is py3, then the approach is totally
different and this PR should be reverted and py3 support should be pursued
without even thinking of py2.

On 22 October 2015 at 22:23, Thomas S Hatch notifications@github.com
wrote:

> py2 still works :) yes there would be a lot to get it on py3, but if it
> works on py3 we don't need py2 anymore
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thatch45/sorbic/pull/4#issuecomment-150360438.

## 

Pedro Algarvio

**Comment by thatch45** [comment]
yes, I think that we should completely abandon py3 for sorbic, so no six needed. The binary vs unicode issue could be very deep though, although did py 3.5 introduce more meathods back into bytestrings?

**Comment by thatch45** [comment]
Basically, I am ok with sorbic being py 3.5 or higher

**Comment by s0undt3ch** [comment]
That's a good goal... Py3 all the way!

**Comment by thatch45** [comment]
yes, I would not use this for anything less than py3 projects

**Pull request merged**
